name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_api_key: ${{74c1112c-d16f-446c-9b6f-ee3315b7ec8b}}
          heroku_app_name: "bastienp7-api"
          heroku_email: "boyer_bastien@msn.com"
          usedocker: true
